version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.11"

sphinx:
  configuration: docs/conf.py

python:
  install:
    - requirements: docs/requirements.txt   # sphinx + doc tools
    - requirements: cosie/extra_requirements.txt   # <- your special file
    - method: pip
      path: .   # install your repo (so autodoc finds cosie)

